export const staticVenuesData = [
  // ─── Houses Category ────────────────────────────────────
  {
    id: 1,
    nameKey: "skylinePenthouse" as const,
    locationKey: "vakeTbilisi" as const,
    price: 450,
    guests: 30,
    latitude: 41.7189,
    longitude: 44.7714,
    image: "/images/venues/skyline-penthouse.jpg",
    images: [
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/seaside-villa.jpg",
    ],
    description: "Modern penthouse with stunning city views",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Houses",
  },
  {
    id: 2,
    nameKey: "gardenVilla" as const,
    locationKey: "saburtaloTbilisi" as const,
    price: 680,
    guests: 50,
    latitude: 41.7372,
    longitude: 44.7654,
    image: "/images/venues/garden-villa.jpg",
    images: [
      "/images/venues/garden-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Spacious villa with beautiful garden",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Houses",
  },
  {
    id: 3,
    nameKey: "rooftopTerrace" as const,
    locationKey: "oldTownTbilisi" as const,
    price: 320,
    guests: 25,
    latitude: 41.7142,
    longitude: 44.8127,
    image: "/images/venues/rooftop-terrace.jpg",
    images: [
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
    ],
    description: "Charming rooftop with panoramic views",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
    category: "Houses",
  },
  {
    id: 4,
    nameKey: "loftStudio" as const,
    locationKey: "veraTbilisi" as const,
    price: 280,
    guests: 20,
    latitude: 41.7415,
    longitude: 44.7952,
    image: "/images/venues/loft-studio.jpg",
    images: [
      "/images/venues/loft-studio.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Contemporary loft space with industrial design",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
    category: "Houses",
  },
  {
    id: 5,
    nameKey: "seasideVilla" as const,
    locationKey: "batumi" as const,
    price: 890,
    guests: 60,
    latitude: 41.6342,
    longitude: 41.6297,
    image: "/images/venues/seaside-villa.jpg",
    images: [
      "/images/venues/seaside-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Luxury seaside villa with private beach access",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Houses",
  },
  {
    id: 6,
    nameKey: "mountainRetreat" as const,
    locationKey: "borjomi" as const,
    price: 520,
    guests: 35,
    latitude: 41.8547,
    longitude: 43.4089,
    image: "/images/venues/mountain-retreat.jpg",
    images: [
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Peaceful mountain retreat surrounded by nature",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
    category: "Houses",
  },

  // ─── Birthday Centers Category ──────────────────────────
  {
    id: 7,
    nameKey: "funZoneBirthdayCenter" as const,
    locationKey: "saburtaloTbilisi" as const,
    price: 350,
    guests: 40,
    latitude: 41.7345,
    longitude: 44.7612,
    image: "/images/venues/rooftop-terrace.jpg",
    images: [
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/loft-studio.jpg",
      "/images/venues/seaside-villa.jpg",
    ],
    description: "Vibrant party center with themed rooms and play areas",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Birthday Centers",
  },
  {
    id: 8,
    nameKey: "happyKidsBirthdayHall" as const,
    locationKey: "vakeTbilisi" as const,
    price: 290,
    guests: 35,
    latitude: 41.7198,
    longitude: 44.7735,
    image: "/images/venues/garden-villa.jpg",
    images: [
      "/images/venues/garden-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Colorful birthday hall with games and entertainment",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
    category: "Birthday Centers",
  },
  {
    id: 9,
    nameKey: "celebrationStation" as const,
    locationKey: "oldTownTbilisi" as const,
    price: 420,
    guests: 50,
    latitude: 41.7155,
    longitude: 44.8098,
    image: "/images/venues/loft-studio.jpg",
    images: [
      "/images/venues/loft-studio.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Modern celebration space with party packages included",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Birthday Centers",
  },
  {
    id: 10,
    nameKey: "starPartyVenue" as const,
    locationKey: "batumi" as const,
    price: 380,
    guests: 45,
    latitude: 41.6355,
    longitude: 41.6310,
    image: "/images/venues/seaside-villa.jpg",
    images: [
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/mountain-retreat.jpg",
    ],
    description: "Seaside birthday venue with outdoor play zone",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
    category: "Birthday Centers",
  },

  // ─── Spaces Category ───────────────────────────────────
  {
    id: 11,
    nameKey: "coworkCreativeHub" as const,
    locationKey: "vakeTbilisi" as const,
    price: 200,
    guests: 25,
    latitude: 41.7201,
    longitude: 44.7720,
    image: "/images/venues/loft-studio.jpg",
    images: [
      "/images/venues/loft-studio.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
    ],
    description: "Creative coworking hub with open floor plan",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Spaces",
  },
  {
    id: 12,
    nameKey: "galleryEventSpace" as const,
    locationKey: "oldTownTbilisi" as const,
    price: 550,
    guests: 80,
    latitude: 41.7148,
    longitude: 44.8110,
    image: "/images/venues/skyline-penthouse.jpg",
    images: [
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/loft-studio.jpg",
    ],
    description: "Gallery-style event space for exhibitions and receptions",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Spaces",
  },
  {
    id: 13,
    nameKey: "openAirPavilion" as const,
    locationKey: "saburtaloTbilisi" as const,
    price: 340,
    guests: 45,
    latitude: 41.7360,
    longitude: 44.7640,
    image: "/images/venues/garden-villa.jpg",
    images: [
      "/images/venues/garden-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/rooftop-terrace.jpg",
    ],
    description: "Open-air pavilion perfect for workshops and gatherings",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
    category: "Spaces",
  },
  {
    id: 14,
    nameKey: "minimalistStudio" as const,
    locationKey: "veraTbilisi" as const,
    price: 180,
    guests: 15,
    latitude: 41.7420,
    longitude: 44.7960,
    image: "/images/venues/rooftop-terrace.jpg",
    images: [
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/loft-studio.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
    ],
    description: "Minimalist studio for intimate meetings and photo shoots",
    amenities: ["wifi", "kitchen", "heating"],
    premium: false,
    category: "Spaces",
  },
  {
    id: 15,
    nameKey: "seasideConferenceHall" as const,
    locationKey: "batumi" as const,
    price: 720,
    guests: 100,
    latitude: 41.6350,
    longitude: 41.6305,
    image: "/images/venues/seaside-villa.jpg",
    images: [
      "/images/venues/seaside-villa.jpg",
      "/images/venues/skyline-penthouse.jpg",
      "/images/venues/rooftop-terrace.jpg",
      "/images/venues/garden-villa.jpg",
      "/images/venues/mountain-retreat.jpg",
    ],
    description: "Premium seaside conference hall with panoramic views",
    amenities: ["wifi", "kitchen", "heating"],
    premium: true,
    category: "Spaces",
  },
]
